### ISSUE TITLE
Invalid URL in README Installation

### ISSUE THREAD

**Issue by pokryfka** [slashmo/gsoc-swift-baggage-context#12]
While the package name has been changed, the URL of the repository remained the same.

Correct dependency:

```swift
        .package(
          name: "swift-baggage-context",
          url: "https://github.com/slashmo/gsoc-swift-baggage-context.git",
            .upToNextMinor(from: "0.1.0")
        ),
```

**Comment by ktoso** [comment]
This was changed already, what do you mean?
https://github.com/slashmo/gsoc-swift-baggage-context/commit/349804a0599573d09df6e433cb8266b80727e5b0

**Comment by ktoso** [comment]
Ah repo url wrong... I'll fix that.

cc @slashmo

**Comment by ktoso** [comment]
Thanks, fixed

**Comment by slashmo** [comment]
Shoot, my bad 🤦‍♂️ Thanks for reporting and thanks for fixing it 👍
